version: '3.8'

# Docker Compose для standalone режима с отдельными сервисами VAD и Button
# Используйте это только если нужно запускать боты отдельно от основного приложения

services:
  # FastAPI основное приложение
  app:
    build: .
    container_name: fluentgo_app
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./users.db:/app/users.db
    ports:
      - "8055:8055"
    networks:
      - fluentgo_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8055/api/test-db')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # VAD Realtime сервис (standalone)
  vad:
    build:
      context: .
      dockerfile: vad_realtime/Dockerfile
    container_name: fluentgo_vad
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./users.db:/app/users.db
      - ./temp:/app/temp
    ports:
      - "8000:8000"
    networks:
      - fluentgo_network
    depends_on:
      - app

  # Button Realtime сервис (standalone)
  button:
    build:
      context: .
      dockerfile: button_realtime/Dockerfile
    container_name: fluentgo_button
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./users.db:/app/users.db
      - ./temp:/app/temp
    ports:
      - "8001:8001"
    networks:
      - fluentgo_network
    depends_on:
      - app

  # Nginx прокси
  nginx:
    image: nginx:alpine
    container_name: fluentgo_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - fluentgo_network
    depends_on:
      - app
      - vad
      - button
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis для кэширования
  redis:
    image: redis:alpine
    container_name: fluentgo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fluentgo_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  fluentgo_network:
    driver: bridge

volumes:
  redis_data:
    driver: local

